name = "Tk Mc Modpack"
author = "Tk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e83ac81dc8e3b2412bdbb6d0dedc3d6f4c2b4f887f802bd7ecafa79cf45a38b8"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
datapack-folder = "datapacks/*"
