name = "Vanilla"
author = "TK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "569ade37c1a6e3bc35222da8fc7e3c4cff37433ffcff6fb5ab1c36deee93679f"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"

[options]
datapack-folder = "datapacks/*"
