name = "Tk Mc Modpack"
author = "Tk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14f444a80f0c80b07b62deebe8510eeeb729a018acb4e734d6f4e638355e2b68"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
datapack-folder = "datapacks/*"
