name = "Tk Mc Modpack"
author = "Tk"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27c84226205d505a49e4350cda5a61c0d0adb8dbe0cb488a842ff590c0f039ac"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
datapack-folder = "datapacks/*"
