name = "Vanilla"
author = "TK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb222d38683f245a3c53650f46d17b999c94c3e989dbe51c1c52b40d70bb75c6"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.7", "1.21.8"]
datapack-folder = "world/datapacks/"
